### ISSUE TITLE
Ctrl keys are named differently

### ISSUE THREAD

**Issue by eikaramba** [emilyrose/hidstream#3]
Although l_control seems to be named consistenly throughout the lib, r_ctrl is sometimes named r_shift or r_control.

e.g. in the modifiers array it is initialized with r_ctrl. but later accessed with modifiers.r_control.

**Comment by emilyrose** [comment]
Thank you for noticing this :smile_cat: I recently merged a PR that I probably didn't test as thoroughly as I should have. I'll work in a fix for this.

**Comment by eikaramba** [comment]
hehe no problem, you're welcome. I think about using your library for a small project, so maybe i might be able to send a few PR myself, if there is anything.

**Comment by emilyrose** [comment]
@eikaramba I believe this should fix it:
https://github.com/emilyrose/hidstream/commit/a3c300c06eeb7641d5dcd6a985b066940a340784#diff-3fab227e34d65fe9bb2d6ea53eec41cfR10 :smile_cat:  

I have tested it briefly with one of my projects which depends on  hidstream, and it is working properly! Let me know what you think! I fixed one other thing as well, which was preventing the keyboard parser from emitting "empty" key events for some reason.

I bumped the version to 2.0.0 just because it changes they keyboard parser's functionality.
